version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - backend_data:/usr/src/app/backups
      - ./backend/database.db:/usr/src/app/database.db
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
volumes:
  backend_data:

networks:
  app-network:
    driver: bridge
